// Flat-key i18n dictionary. UI reads via useT().
// Add a key here in every supported language whenever you add a UI string.
// Payload content (from page_objects) is already localized by the backend
// and is NOT translated here.

export type UiLang = "en" | "uk";

const en = {
  // Navigation
  "nav.dashboard": "Dashboard",
  "nav.database": "Database",
  "nav.competitors": "Competitor Radar",
  "nav.analyses": "Account Analyses",
  "nav.insights": "Insights",
  "nav.todos": "To Dos",
  "nav.ideas": "Ideas",
  "nav.formats": "Formats",
  "nav.performance": "My Performance",
  "nav.trends": "Trends",
  "nav.setup": "Setup",
  "nav.settings": "Settings",

  // Role switcher
  "role.owner": "Owner",
  "role.marketer": "Marketer",
  "role.smm": "SMM",
  "role.owner_desc": "Strategy & outcomes",
  "role.marketer_desc": "Funnels & KPIs",
  "role.smm_desc": "Formats & hooks",
  "role.tailored": "View tailored for the selected role",

  // Platform switcher
  "platform.all": "All",
  "platform.facebook_soon": "Facebook — coming soon",
  "platform.maps_soon": "Maps — coming soon",

  // Language switcher
  "lang.label": "Language",
  "lang.en": "EN",
  "lang.uk": "UA",

  // Empty page-object state
  "empty.title": "Analysis pending for the {role} view",
  "empty.body": "We're still preparing the {page} view for the {role} role. It will fill in automatically once the latest analysis pass completes.",
  "empty.last_generated": "Last generated: {when}",
  "empty.recheck": "Re-check",

  // Pending page-object state (data_status != ready)
  "pending.title": "Preparing your data…",
  "pending.body": "Our AI is crunching the latest numbers. This usually takes a few minutes — the page will refresh automatically.",

  // Dashboard
  "dashboard.loading": "Loading dashboard…",
  "dashboard.greeting": "Hey {name} 👋",
  "dashboard.subtitle_fallback": "Your daily snapshot of reach, engagement and what to ship next.",
  "dashboard.view_insights": "View today's insights",
  "dashboard.top_insight_badge": "⚡ Top insight today",
  "dashboard.trend_title": "You vs your niche",
  "dashboard.trend_subtitle": "Estimated reach, last 14 days",
  "dashboard.you": "You",
  "dashboard.niche_avg": "Niche avg",
  "dashboard.spotlight_title": "Competitor spotlight",
  "dashboard.wins_title": "Your recent wins 🎉",
  "dashboard.wins_subtitle": "Posts that beat your 30-day average",
  "dashboard.view_all": "View all",
  "dashboard.what_works": "What works",
  "dashboard.what_fails": "What fails",
  "dashboard.apply_strategy": "Apply to my strategy",

  // Competitors
  "competitors.loading": "Loading competitors…",
  "competitors.title": "Competitor Radar",
  "competitors.headline_fallback": "{n} accounts scored across 12 dimensions",
  "competitors.compare_two": "Compare two",
  "competitors.add": "+ Add competitor",
  "competitors.you_badge": "You",
  "competitors.open": "Open",
  "competitors.strength": "Strength",
  "competitors.weakness": "Weakness",
  "competitors.h2h_title": "You vs {top}",
  "competitors.h2h_subtitle": "12-dimension head-to-head from the latest radar pass",
  "competitors.delta_overall": "Δ {n} overall",
  "competitors.stat.overall": "Overall",
  "competitors.stat.hook": "Hook",
  "competitors.stat.visual": "Visual",
  "competitors.stat.trust": "Trust",

  // Account analyses
  "analyses.loading": "Loading analyses…",
  "analyses.title": "Account Analyses",
  "analyses.subtitle": "{n} deep dives · positioning, SWOT and strategic recommendations",
  "analyses.search_ph": "Search positioning, hooks, pillars…",
  "analyses.score": "Score {n}",
  "analyses.positioning": "Positioning",
  "analyses.pillars": "Content pillars",
  "analyses.strongest_formats": "Strongest formats",
  "analyses.weakest_formats": "Weakest formats",
  "analyses.main_hooks": "Main hooks",
  "analyses.tone": "Tone of voice",
  "analyses.visual_identity": "Visual identity",
  "analyses.pain": "Audience pain points",
  "analyses.ctas": "Main CTAs",
  "analyses.product": "Product angle",
  "analyses.trust": "Trust signals",
  "analyses.community": "Community signals",
  "analyses.strengths": "Strengths",
  "analyses.weaknesses": "Weaknesses",
  "analyses.opportunities": "Opportunities",
  "analyses.threats": "Threats",
  "analyses.copy": "Best patterns to copy",
  "analyses.avoid": "Things to avoid",
  "analyses.summary": "Strategic summary",
  "analyses.save_idea": "Save to ideas",
  "analyses.turn_todo": "Turn into to-do",
  "analyses.no_match": "No analyses match \u201C{q}\u201D.",

  // Database
  "database.title": "Database",
  "database.subtitle": "Executive overview of the workspace, generated by the analysis layer.",

  // Settings
  "settings.title": "Settings",
  "settings.subtitle": "Language, notifications, and how Navio reaches you.",

  // Best Outcomes
  "best_outcomes.loading": "Loading…",
  "best_outcomes.title": "Best Competitor Outcomes",
  "best_outcomes.pattern_title": "Key patterns",
  "best_outcomes.top_posts_title": "Top performing posts",

  // Competitor Moves
  "competitor_moves.loading": "Loading…",
  "competitor_moves.title": "Competitor Moves",

  // Dynamics
  "dynamics.loading": "Loading…",
  "dynamics.title": "Dynamics",

  // Navigation (new)
  "nav.best_outcomes": "Best Posts",
  "nav.competitor_moves": "Competitor Moves",
  "nav.dynamics": "Dynamics",

  // Common
  "common.loading": "Loading…",
} as const;

const uk: Record<keyof typeof en, string> = {
  "nav.dashboard": "Дашборд",
  "nav.database": "База даних",
  "nav.competitors": "Радар конкурентів",
  "nav.analyses": "Аналізи акаунтів",
  "nav.insights": "Інсайти",
  "nav.todos": "Завдання",
  "nav.ideas": "Ідеї",
  "nav.formats": "Формати",
  "nav.performance": "Моя ефективність",
  "nav.trends": "Тренди",
  "nav.setup": "Налаштування",
  "nav.settings": "Параметри",

  "role.owner": "Власник",
  "role.marketer": "Маркетолог",
  "role.smm": "SMM",
  "role.owner_desc": "Стратегія та результати",
  "role.marketer_desc": "Воронки та KPI",
  "role.smm_desc": "Формати та хуки",
  "role.tailored": "Вигляд адаптовано під обрану роль",

  "platform.all": "Усі",
  "platform.facebook_soon": "Facebook — незабаром",
  "platform.maps_soon": "Maps — незабаром",

  "lang.label": "Мова",
  "lang.en": "EN",
  "lang.uk": "UA",

  "empty.title": "Аналіз для ролі «{role}» ще готується",
  "empty.body": "Ми ще готуємо сторінку {page} для ролі {role}. Вона заповниться автоматично, щойно завершиться наступний прохід аналізу.",
  "empty.last_generated": "Востаннє оновлено: {when}",
  "empty.recheck": "Перевірити ще раз",

  "pending.title": "Готуємо ваші дані…",
  "pending.body": "ШІ обробляє останні дані. Зазвичай це займає кілька хвилин — сторінка оновиться автоматично.",

  "dashboard.loading": "Завантаження дашборду…",
  "dashboard.greeting": "Привіт, {name} 👋",
  "dashboard.subtitle_fallback": "Щоденний зріз охоплення, залученості й того, що варто опублікувати далі.",
  "dashboard.view_insights": "Інсайти на сьогодні",
  "dashboard.top_insight_badge": "⚡ Інсайт дня",
  "dashboard.trend_title": "Ви vs ніша",
  "dashboard.trend_subtitle": "Прогнозоване охоплення за останні 14 днів",
  "dashboard.you": "Ви",
  "dashboard.niche_avg": "Сер. по ніші",
  "dashboard.spotlight_title": "Конкурент у фокусі",
  "dashboard.wins_title": "Ваші перемоги 🎉",
  "dashboard.wins_subtitle": "Пости, що перевершили середнє за 30 днів",
  "dashboard.view_all": "Усі",
  "dashboard.what_works": "Що працює",
  "dashboard.what_fails": "Що не працює",
  "dashboard.apply_strategy": "Застосувати у стратегії",

  "competitors.loading": "Завантаження конкурентів…",
  "competitors.title": "Радар конкурентів",
  "competitors.headline_fallback": "{n} акаунтів оцінено за 12 вимірами",
  "competitors.compare_two": "Порівняти двох",
  "competitors.add": "+ Додати конкурента",
  "competitors.you_badge": "Ви",
  "competitors.open": "Відкрити",
  "competitors.strength": "Сила",
  "competitors.weakness": "Слабкість",
  "competitors.h2h_title": "Ви vs {top}",
  "competitors.h2h_subtitle": "Порівняння за 12 вимірами з останнього проходу радару",
  "competitors.delta_overall": "Δ {n} загалом",
  "competitors.stat.overall": "Загальний",
  "competitors.stat.hook": "Хук",
  "competitors.stat.visual": "Візуал",
  "competitors.stat.trust": "Довіра",

  "analyses.loading": "Завантаження аналізів…",
  "analyses.title": "Аналізи акаунтів",
  "analyses.subtitle": "{n} глибоких розборів · позиціонування, SWOT і стратегічні рекомендації",
  "analyses.search_ph": "Пошук за позиціонуванням, хуками, рубриками…",
  "analyses.score": "Оцінка {n}",
  "analyses.positioning": "Позиціонування",
  "analyses.pillars": "Контент-рубрики",
  "analyses.strongest_formats": "Найсильніші формати",
  "analyses.weakest_formats": "Найслабші формати",
  "analyses.main_hooks": "Основні хуки",
  "analyses.tone": "Тон голосу",
  "analyses.visual_identity": "Візуальна ідентичність",
  "analyses.pain": "Болі аудиторії",
  "analyses.ctas": "Основні CTA",
  "analyses.product": "Продуктовий кут",
  "analyses.trust": "Сигнали довіри",
  "analyses.community": "Сигнали спільноти",
  "analyses.strengths": "Сильні сторони",
  "analyses.weaknesses": "Слабкі сторони",
  "analyses.opportunities": "Можливості",
  "analyses.threats": "Загрози",
  "analyses.copy": "Що варто скопіювати",
  "analyses.avoid": "Чого уникати",
  "analyses.summary": "Стратегічний підсумок",
  "analyses.save_idea": "Зберегти в ідеї",
  "analyses.turn_todo": "Перетворити на завдання",
  "analyses.no_match": "Немає аналізів за запитом «{q}».",

  "database.title": "База даних",
  "database.subtitle": "Виконавчий огляд робочого простору, згенерований аналітичним шаром.",

  "settings.title": "Параметри",
  "settings.subtitle": "Мова, сповіщення та як з вами зв'язується Navio.",

  "best_outcomes.loading": "Завантаження…",
  "best_outcomes.title": "Кращі результати конкурентів",
  "best_outcomes.pattern_title": "Ключові патерни",
  "best_outcomes.top_posts_title": "Топ пости конкурентів",

  "competitor_moves.loading": "Завантаження…",
  "competitor_moves.title": "Ходи конкурентів",

  "dynamics.loading": "Завантаження…",
  "dynamics.title": "Динаміка",

  "nav.best_outcomes": "Кращі пости",
  "nav.competitor_moves": "Ходи конкурентів",
  "nav.dynamics": "Динаміка",

  "common.loading": "Завантаження…",
};

export const dictionaries: Record<UiLang, Record<string, string>> = { en, uk };

export type TranslationKey = keyof typeof en;
