/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTrendsRouteImport } from './routes/app.trends'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppHypothesesRouteImport } from './routes/app.hypotheses'
import { Route as AppDynamicsRouteImport } from './routes/app.dynamics'
import { Route as AppConnectedRouteImport } from './routes/app.connected'
import { Route as AppCompetitorsRouteImport } from './routes/app.competitors'
import { Route as AppCompetitorMovesRouteImport } from './routes/app.competitor-moves'
import { Route as AppBestOutcomesRouteImport } from './routes/app.best-outcomes'
import { Route as AppDebugPageObjectsRouteImport } from './routes/app.debug.page-objects'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppHypothesesRoute = AppHypothesesRouteImport.update({
  id: '/hypotheses',
  path: '/hypotheses',
  getParentRoute: () => AppRoute,
} as any)
const AppDynamicsRoute = AppDynamicsRouteImport.update({
  id: '/dynamics',
  path: '/dynamics',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectedRoute = AppConnectedRouteImport.update({
  id: '/connected',
  path: '/connected',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorMovesRoute = AppCompetitorMovesRouteImport.update({
  id: '/competitor-moves',
  path: '/competitor-moves',
  getParentRoute: () => AppRoute,
} as any)
const AppBestOutcomesRoute = AppBestOutcomesRouteImport.update({
  id: '/best-outcomes',
  path: '/best-outcomes',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugPageObjectsRoute = AppDebugPageObjectsRouteImport.update({
  id: '/debug/page-objects',
  path: '/debug/page-objects',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/best-outcomes': typeof AppBestOutcomesRoute
  '/app/competitor-moves': typeof AppCompetitorMovesRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/connected': typeof AppConnectedRoute
  '/app/dynamics': typeof AppDynamicsRoute
  '/app/hypotheses': typeof AppHypothesesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
  '/app/debug/page-objects': typeof AppDebugPageObjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/best-outcomes': typeof AppBestOutcomesRoute
  '/app/competitor-moves': typeof AppCompetitorMovesRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/connected': typeof AppConnectedRoute
  '/app/dynamics': typeof AppDynamicsRoute
  '/app/hypotheses': typeof AppHypothesesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trends': typeof AppTrendsRoute
  '/app': typeof AppIndexRoute
  '/app/debug/page-objects': typeof AppDebugPageObjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/best-outcomes': typeof AppBestOutcomesRoute
  '/app/competitor-moves': typeof AppCompetitorMovesRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/connected': typeof AppConnectedRoute
  '/app/dynamics': typeof AppDynamicsRoute
  '/app/hypotheses': typeof AppHypothesesRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
  '/app/debug/page-objects': typeof AppDebugPageObjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/app/best-outcomes'
    | '/app/competitor-moves'
    | '/app/competitors'
    | '/app/connected'
    | '/app/dynamics'
    | '/app/hypotheses'
    | '/app/performance'
    | '/app/settings'
    | '/app/trends'
    | '/app/'
    | '/app/debug/page-objects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/app/best-outcomes'
    | '/app/competitor-moves'
    | '/app/competitors'
    | '/app/connected'
    | '/app/dynamics'
    | '/app/hypotheses'
    | '/app/performance'
    | '/app/settings'
    | '/app/trends'
    | '/app'
    | '/app/debug/page-objects'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/app/best-outcomes'
    | '/app/competitor-moves'
    | '/app/competitors'
    | '/app/connected'
    | '/app/dynamics'
    | '/app/hypotheses'
    | '/app/performance'
    | '/app/settings'
    | '/app/trends'
    | '/app/'
    | '/app/debug/page-objects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trends': {
      id: '/app/trends'
      path: '/trends'
      fullPath: '/app/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hypotheses': {
      id: '/app/hypotheses'
      path: '/hypotheses'
      fullPath: '/app/hypotheses'
      preLoaderRoute: typeof AppHypothesesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dynamics': {
      id: '/app/dynamics'
      path: '/dynamics'
      fullPath: '/app/dynamics'
      preLoaderRoute: typeof AppDynamicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connected': {
      id: '/app/connected'
      path: '/connected'
      fullPath: '/app/connected'
      preLoaderRoute: typeof AppConnectedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitors': {
      id: '/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitor-moves': {
      id: '/app/competitor-moves'
      path: '/competitor-moves'
      fullPath: '/app/competitor-moves'
      preLoaderRoute: typeof AppCompetitorMovesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/best-outcomes': {
      id: '/app/best-outcomes'
      path: '/best-outcomes'
      fullPath: '/app/best-outcomes'
      preLoaderRoute: typeof AppBestOutcomesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debug/page-objects': {
      id: '/app/debug/page-objects'
      path: '/debug/page-objects'
      fullPath: '/app/debug/page-objects'
      preLoaderRoute: typeof AppDebugPageObjectsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBestOutcomesRoute: typeof AppBestOutcomesRoute
  AppCompetitorMovesRoute: typeof AppCompetitorMovesRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppConnectedRoute: typeof AppConnectedRoute
  AppDynamicsRoute: typeof AppDynamicsRoute
  AppHypothesesRoute: typeof AppHypothesesRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDebugPageObjectsRoute: typeof AppDebugPageObjectsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBestOutcomesRoute: AppBestOutcomesRoute,
  AppCompetitorMovesRoute: AppCompetitorMovesRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppConnectedRoute: AppConnectedRoute,
  AppDynamicsRoute: AppDynamicsRoute,
  AppHypothesesRoute: AppHypothesesRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppIndexRoute: AppIndexRoute,
  AppDebugPageObjectsRoute: AppDebugPageObjectsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
