/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTrendsRouteImport } from './routes/app.trends'
import { Route as AppTodosRouteImport } from './routes/app.todos'
import { Route as AppSetupRouteImport } from './routes/app.setup'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPerformanceRouteImport } from './routes/app.performance'
import { Route as AppInsightsRouteImport } from './routes/app.insights'
import { Route as AppIdeasRouteImport } from './routes/app.ideas'
import { Route as AppHypothesesRouteImport } from './routes/app.hypotheses'
import { Route as AppFormatsRouteImport } from './routes/app.formats'
import { Route as AppDynamicsRouteImport } from './routes/app.dynamics'
import { Route as AppDatabaseRouteImport } from './routes/app.database'
import { Route as AppCompetitorsRouteImport } from './routes/app.competitors'
import { Route as AppCompetitorMovesRouteImport } from './routes/app.competitor-moves'
import { Route as AppBestOutcomesRouteImport } from './routes/app.best-outcomes'
import { Route as AppAnalysesRouteImport } from './routes/app.analyses'
import { Route as AppDebugPageObjectsRouteImport } from './routes/app.debug.page-objects'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTrendsRoute = AppTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AppRoute,
} as any)
const AppTodosRoute = AppTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppIdeasRoute = AppIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AppRoute,
} as any)
const AppHypothesesRoute = AppHypothesesRouteImport.update({
  id: '/hypotheses',
  path: '/hypotheses',
  getParentRoute: () => AppRoute,
} as any)
const AppFormatsRoute = AppFormatsRouteImport.update({
  id: '/formats',
  path: '/formats',
  getParentRoute: () => AppRoute,
} as any)
const AppDynamicsRoute = AppDynamicsRouteImport.update({
  id: '/dynamics',
  path: '/dynamics',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabaseRoute = AppDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorMovesRoute = AppCompetitorMovesRouteImport.update({
  id: '/competitor-moves',
  path: '/competitor-moves',
  getParentRoute: () => AppRoute,
} as any)
const AppBestOutcomesRoute = AppBestOutcomesRouteImport.update({
  id: '/best-outcomes',
  path: '/best-outcomes',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalysesRoute = AppAnalysesRouteImport.update({
  id: '/analyses',
  path: '/analyses',
  getParentRoute: () => AppRoute,
} as any)
const AppDebugPageObjectsRoute = AppDebugPageObjectsRouteImport.update({
  id: '/debug/page-objects',
  path: '/debug/page-objects',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/analyses': typeof AppAnalysesRoute
  '/app/best-outcomes': typeof AppBestOutcomesRoute
  '/app/competitor-moves': typeof AppCompetitorMovesRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/database': typeof AppDatabaseRoute
  '/app/dynamics': typeof AppDynamicsRoute
  '/app/formats': typeof AppFormatsRoute
  '/app/hypotheses': typeof AppHypothesesRoute
  '/app/ideas': typeof AppIdeasRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/todos': typeof AppTodosRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
  '/app/debug/page-objects': typeof AppDebugPageObjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/analyses': typeof AppAnalysesRoute
  '/app/best-outcomes': typeof AppBestOutcomesRoute
  '/app/competitor-moves': typeof AppCompetitorMovesRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/database': typeof AppDatabaseRoute
  '/app/dynamics': typeof AppDynamicsRoute
  '/app/formats': typeof AppFormatsRoute
  '/app/hypotheses': typeof AppHypothesesRoute
  '/app/ideas': typeof AppIdeasRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/todos': typeof AppTodosRoute
  '/app/trends': typeof AppTrendsRoute
  '/app': typeof AppIndexRoute
  '/app/debug/page-objects': typeof AppDebugPageObjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/analyses': typeof AppAnalysesRoute
  '/app/best-outcomes': typeof AppBestOutcomesRoute
  '/app/competitor-moves': typeof AppCompetitorMovesRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/database': typeof AppDatabaseRoute
  '/app/dynamics': typeof AppDynamicsRoute
  '/app/formats': typeof AppFormatsRoute
  '/app/hypotheses': typeof AppHypothesesRoute
  '/app/ideas': typeof AppIdeasRoute
  '/app/insights': typeof AppInsightsRoute
  '/app/performance': typeof AppPerformanceRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/setup': typeof AppSetupRoute
  '/app/todos': typeof AppTodosRoute
  '/app/trends': typeof AppTrendsRoute
  '/app/': typeof AppIndexRoute
  '/app/debug/page-objects': typeof AppDebugPageObjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/app/analyses'
    | '/app/best-outcomes'
    | '/app/competitor-moves'
    | '/app/competitors'
    | '/app/database'
    | '/app/dynamics'
    | '/app/formats'
    | '/app/hypotheses'
    | '/app/ideas'
    | '/app/insights'
    | '/app/performance'
    | '/app/settings'
    | '/app/setup'
    | '/app/todos'
    | '/app/trends'
    | '/app/'
    | '/app/debug/page-objects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/app/analyses'
    | '/app/best-outcomes'
    | '/app/competitor-moves'
    | '/app/competitors'
    | '/app/database'
    | '/app/dynamics'
    | '/app/formats'
    | '/app/hypotheses'
    | '/app/ideas'
    | '/app/insights'
    | '/app/performance'
    | '/app/settings'
    | '/app/setup'
    | '/app/todos'
    | '/app/trends'
    | '/app'
    | '/app/debug/page-objects'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/app/analyses'
    | '/app/best-outcomes'
    | '/app/competitor-moves'
    | '/app/competitors'
    | '/app/database'
    | '/app/dynamics'
    | '/app/formats'
    | '/app/hypotheses'
    | '/app/ideas'
    | '/app/insights'
    | '/app/performance'
    | '/app/settings'
    | '/app/setup'
    | '/app/todos'
    | '/app/trends'
    | '/app/'
    | '/app/debug/page-objects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trends': {
      id: '/app/trends'
      path: '/trends'
      fullPath: '/app/trends'
      preLoaderRoute: typeof AppTrendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/todos': {
      id: '/app/todos'
      path: '/todos'
      fullPath: '/app/todos'
      preLoaderRoute: typeof AppTodosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/setup': {
      id: '/app/setup'
      path: '/setup'
      fullPath: '/app/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/performance': {
      id: '/app/performance'
      path: '/performance'
      fullPath: '/app/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/insights': {
      id: '/app/insights'
      path: '/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ideas': {
      id: '/app/ideas'
      path: '/ideas'
      fullPath: '/app/ideas'
      preLoaderRoute: typeof AppIdeasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hypotheses': {
      id: '/app/hypotheses'
      path: '/hypotheses'
      fullPath: '/app/hypotheses'
      preLoaderRoute: typeof AppHypothesesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/formats': {
      id: '/app/formats'
      path: '/formats'
      fullPath: '/app/formats'
      preLoaderRoute: typeof AppFormatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dynamics': {
      id: '/app/dynamics'
      path: '/dynamics'
      fullPath: '/app/dynamics'
      preLoaderRoute: typeof AppDynamicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/database': {
      id: '/app/database'
      path: '/database'
      fullPath: '/app/database'
      preLoaderRoute: typeof AppDatabaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitors': {
      id: '/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitor-moves': {
      id: '/app/competitor-moves'
      path: '/competitor-moves'
      fullPath: '/app/competitor-moves'
      preLoaderRoute: typeof AppCompetitorMovesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/best-outcomes': {
      id: '/app/best-outcomes'
      path: '/best-outcomes'
      fullPath: '/app/best-outcomes'
      preLoaderRoute: typeof AppBestOutcomesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analyses': {
      id: '/app/analyses'
      path: '/analyses'
      fullPath: '/app/analyses'
      preLoaderRoute: typeof AppAnalysesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debug/page-objects': {
      id: '/app/debug/page-objects'
      path: '/debug/page-objects'
      fullPath: '/app/debug/page-objects'
      preLoaderRoute: typeof AppDebugPageObjectsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalysesRoute: typeof AppAnalysesRoute
  AppBestOutcomesRoute: typeof AppBestOutcomesRoute
  AppCompetitorMovesRoute: typeof AppCompetitorMovesRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppDatabaseRoute: typeof AppDatabaseRoute
  AppDynamicsRoute: typeof AppDynamicsRoute
  AppFormatsRoute: typeof AppFormatsRoute
  AppHypothesesRoute: typeof AppHypothesesRoute
  AppIdeasRoute: typeof AppIdeasRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSetupRoute: typeof AppSetupRoute
  AppTodosRoute: typeof AppTodosRoute
  AppTrendsRoute: typeof AppTrendsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDebugPageObjectsRoute: typeof AppDebugPageObjectsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalysesRoute: AppAnalysesRoute,
  AppBestOutcomesRoute: AppBestOutcomesRoute,
  AppCompetitorMovesRoute: AppCompetitorMovesRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppDatabaseRoute: AppDatabaseRoute,
  AppDynamicsRoute: AppDynamicsRoute,
  AppFormatsRoute: AppFormatsRoute,
  AppHypothesesRoute: AppHypothesesRoute,
  AppIdeasRoute: AppIdeasRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSetupRoute: AppSetupRoute,
  AppTodosRoute: AppTodosRoute,
  AppTrendsRoute: AppTrendsRoute,
  AppIndexRoute: AppIndexRoute,
  AppDebugPageObjectsRoute: AppDebugPageObjectsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
