// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
// ws is required for Node.js < 22 which lacks native WebSocket support
import ws from 'ws'

function decodeJwtPayload(token: string): Record<string, any> | null {
  try {
    const base64 = token.split('.')[1];
    const json = atob(base64.replace(/-/g, '+').replace(/_/g, '/'));
    return JSON.parse(json);
  } catch {
    return null;
  }
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {

    const SUPABASE_URL = process.env.SUPABASE_URL ?? process.env.VITE_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      throw new Error(`Missing Supabase env vars: ${missing.join(', ')}`);
    }

    const request = getRequest();
    console.log('[auth] request headers available:', !!request?.headers);

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');
    console.log('[auth] Authorization header present:', !!authHeader, '| starts with Bearer:', authHeader?.startsWith('Bearer '));

    if (!authHeader?.startsWith('Bearer ')) {
      throw new Error('Unauthorized: No Bearer token provided');
    }

    const token = authHeader.replace('Bearer ', '');
    console.log('[auth] token length:', token.length);

    const claims = decodeJwtPayload(token);
    console.log('[auth] claims decoded:', !!claims, '| sub:', claims?.sub?.slice(0, 8));

    const userId = claims?.sub as string | undefined;
    if (!userId) {
      console.log('[auth] ERROR: no sub in token');
      throw new Error('Unauthorized: No sub in token');
    }
    console.log('[auth] userId OK, creating supabase client...');

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
        realtime: { transport: ws },
      }
    );

    console.log('[auth] calling next()...');
    const result = await next({
      context: {
        supabase,
        userId,
        claims,
      },
    });
    console.log('[auth] next() returned:', typeof result);
    return result;
  },
);
